---
title: "usgs_13296000"
author: "Tao Huang"
date: `r Sys.Date()`
output: html_document
---

# Step 0: Load packages
# Step 1: Load PRISM and USGS

# Step 0: Load packages
```{r include=FALSE}
# install.packages("tidyhydat")
#library(tidyhydat) # for getting ECCC HYDAT data
# download_hydat()
library(dplyr) # for data wrangling and pipelines
library(ggplot2) # for modifying fasstr plots
library("dplyr")
#install.packages('corrplot')
library(corrplot)
library(RColorBrewer)
# install.packages("gbm")
library("gbm")
# install.packages("caret")
library("caret")
#install.packages("pdp")
library("pdp")          # model visualization
library("ggplot2")      # model visualization
#install.packages("lime")
library("lime")         # model visualization
library("pROC")
#install.packages("e1071", repos="http://R-Forge.R-project.org")
library("e1071")
library( "MASS" )    #    used to generate correlated variables
library("sp")
library("Hmisc")    #   used for graphing se bars
#install.packages("e1071")
library(e1071)
library(caret)
library("ModelMetrics")
library("foreign")
#install.packages("rfUtilities")
library("rfUtilities")
library("lubridate")
#  install.packages("feasts")
library(feasts)
library(tsibble)
#  install.packages("TSstudio")
library(TSstudio)
library(plotly)
# third approach
library(tidyverse)
# install.packages("timetk")
library("timetk")
```

# Step 1: Load PRISM and USGS
```{r}
prism_df<-readRDS(" .rds")
summary(prism_df)
```














# Step 1: load the packages
# Step 2: Read PRISM data
# Step 3: Load USGS data




```{r}
prism_df2<-prism_df
prism_df2$yr<-as.character(prism_df$yr)
prism_df2$mo<-as.character(prism_df$mo)
max_ST_yr<-prism_df2 %>% group_by( yr ,  mo  )%>% summarise(max_ST = max(mean_StreamTemp),mean_ST=mean(mean_StreamTemp) )
max_ST_yr[max_ST_yr$mo %in% c("6",  "7" , "8","9"),]
boxplot(max_ST_yr[max_ST_yr$mo %in% c("6",  "7" , "8","9"),]$mean_ST~max_ST_yr[max_ST_yr$mo %in% c("6",  "7" , "8","9"),]$mo, ylab = "Monthly mean stream T (degC)", xlab="Month", main="YANKEE FORK SALMON RIVER NR CLAYTON ID")
```












# Step 5: specify year and month for analysis
```{r}
prism_df<-prism_df[   prism_df$mo %in% c(7,8),]
summary(prism_df)
```

# Step 6: Create the correlation plot
```{r}
prism_df ->daily_df_summer
daily_df_summer$log_median_Q<-daily_df_summer$log_mean_Q
M <-cor( daily_df_summer[,c("mean_StreamTemp"
#                            ,"max_StreamTemp"      
,"log_mean_Q","mean_AirTemperature_C","mean_AirTemperature_C_1","max_AirTemperature_C_1","max_AirTemperature_C","vpdmax","doy")])
M
corrplot(M, type="upper", order="hclust",
         col=brewer.pal(n=8, name="RdYlBu"))
M_1 <-cor( daily_df_summer[,c("mean_StreamTemp" ,"log_mean_Q","mean_AirTemperature_C")])
corrplot(M_1, type="upper", order="hclust",
         col=brewer.pal(n=8, name="RdYlBu"))
```

# Model 2: GBM
```{r}
# set seed for generating random data.
set.seed(0)          
# createDataPartition() function from the caret package to split the original dataset into a training and testing set and split data into training (80%) and testing set (20%)
variables<-c("mean_StreamTemp","mean_AirTemperature_C","log_mean_Q" )
parts = createDataPartition(  daily_df_summer$mean_StreamTemp , p = .8, list = F)
train = daily_df_summer[parts, variables ]
test =  daily_df_summer[-parts, variables  ]
# feature and target array
test_x = test[, -1] 
test_y = test[, 1] 
```

```{r}
model_gbm = gbm(train$mean_StreamTemp      ~.,
                data = train,
                distribution = "gaussian",
                cv.folds = 10,
                shrinkage = .01,
                n.minobsinnode = 10,
                n.trees = 800)
 
# model performance
perf_gbm1 = gbm.perf( model_gbm, method = "cv")
print(model_gbm)
summary(model_gbm)
rinf<-summary(model_gbm)
barplot( rinf$rel.inf , horiz = TRUE, las = 1)
ggplot(rinf, aes(rel.inf)) + geom_bar()
rinf$max_yr<-max(as.numeric(daily_df_summer$yr))
rinf$min_yr<-min(as.numeric(daily_df_summer$yr))
rinf$site_id<- 13296000
rinf
saveRDS(rinf ,file=  "rinf_13296000.rds"  )
```

```{r}
rinf$var<- factor(rinf$var, levels=c(  "mean_AirTemperature_C","log_mean_Q"  ))
ggplot( rinf, aes( var , rel.inf ))+  geom_col()+ 
  coord_flip()
ggplot( rinf )+  geom_bar(  aes( x=var, y= rel.inf),  stat = "summary")+ scale_x_discrete(labels=  c( "mean_AirTemperature_C","log_mean_Q") )+ylab("Relative importance (%)") +xlab(" ")  + theme(text=element_text(size=16))
```

```{r}
#test_y <-test_y$max_StreamTemp
pred_y = predict.gbm(model_gbm, test_x)
residuals =  test_y   - pred_y
summary(test_y )
xlim=c(5,20)
RMSE = sqrt(mean(residuals^2))
cat('The root mean square error of the test data is ', round(RMSE,3),'\n')
y_test_mean = mean( test_y  )
# Calculate total sum of squares
tss =  sum(( test_y   - y_test_mean)^2 )
# Calculate residual sum of squares
rss =  sum(residuals^2)
# Calculate R-squared
rsq  =  1 - (rss/tss)
cat('The R-square of the test data is ', round(rsq,3), '\n')
# visualize the model, actual and predicted data
x_ax = 1:length(pred_y)
plot(x_ax, test_y  , col="blue", pch=20, cex=.9)
lines(x_ax, pred_y, col="red", pch=20, cex=.9) 
plot(  test_y , pred_y,xlim= xlim ,ylim= xlim, xlab="Observed stream temperature (degC)", ylab="Predicted stream temperature (degC)", main="YANKEE FORK SALMON RIVER NR CLAYTON ID")
par(new=T)
x=seq(1,30)
plot(x,x,type="l",xlim= xlim ,ylim= xlim,xlab="",ylab="")
```

```{r}
# ts function is responsible to convert to ts object
daily_df_summer_2017<-daily_df_summer[daily_df_summer$yr==2020,]
ts <- ts(data = daily_df_summer_2017[, c( "mean_AirTemperature_C",  "mean_StreamTemp" )], # selecting 2 variables
   start = 1,
   end =  dim(daily_df_summer_2017)[1],
   frequency = 1)
ts
```

```{r}
ts_plot( ts,
        title = "YANKEE FORK SALMON RIVER NR CLAYTON ID",
        Ytitle =    "mean StreamTemp",
        Xtitle = " ", )
```

```{r}
# ccf time series
par(mfrow=c(1,1))
ccf( ts[, c( "mean_StreamTemp")],  ts[, c( "mean_AirTemperature_C")], 
    lag.max = 11,
    main = "Cros-Correlation Plot",
    ylab = "CCF")
# ccf time series
par(mfrow=c(1,1))
ccf( ts[, c( "mean_AirTemperature_C")],  ts[, c( "mean_StreamTemp")], 
    lag.max = 11,
    main = "Cros-Correlation Plot",
    ylab = "CCF")
```






