---
title: "usgs_13296000"
output: html_document
---

```{r}
st_all_gage<-c("13296000")
```

# Step 1: load the packages
# Step 2: Read PRISM data
# Step 3: Load USGS data

# Step 1: load the packages
```{r include=FALSE}
# install.packages("dataRetrieval")
library("dataRetrieval") # for getting USGS NWIS data
library("lubridate")
library("dplyr") # for data wrangling and pipelines
# #install.packages('corrplot')
library("corrplot")
library("caret")
library("RColorBrewer")
# # install.packages("gbm")
library("gbm")
#  install.packages("TSstudio")
library("TSstudio")

# install.packages("tidyhydat")
# library(tidyhydat) # for getting ECCC HYDAT data
# # download_hydat()


# library(ggplot2) # for modifying fasstr plots






# #install.packages("pdp")
# library("pdp")          # model visualization
# library("ggplot2")      # model visualization
# #install.packages("lime")
# library("lime")         # model visualization
# library("pROC")
# #install.packages("e1071", repos="http://R-Forge.R-project.org")
# library("e1071")
# library( "MASS" )    #    used to generate correlated variables
# library("sp")
# library("Hmisc")    #   used for graphing se bars
# #install.packages("randomForest")
# require("randomForest")
# #install.packages("e1071")
# library(e1071)


# library("ModelMetrics")
# library("foreign")
# #install.packages("rfUtilities")
# library("rfUtilities")


# #  install.packages("feasts")
# library(feasts)
# library(tsibble)


#library(plotly)
# third approach
#library(tidyverse)
# install.packages("timetk")
#library("timetk")
```

# Step 2: Read PRISM data
```{r}
siteINFO <- readNWISsite( st_all_gage )
print(c(siteINFO$dec_lat_va,siteINFO$dec_long_va))
#prism<-read.csv("PRISM_ppt_tmin_tmean_tmax_tdmean_vpdmin_vpdmax.csv")
prism<-read.csv("prism_1981_2023_44.2789_114.7339.csv")
prism$Date <-as.Date(prism$Date, format="%Y-%m-%d")
summary(prism)
```

# Step 3: Load USGS data
```{r}
#create empty tables
meanSummerT_df<-data.frame(
  agency_cd= " ",
  site_no="",
  Date=as.Date("1951-01-01",format="%Y-%m-%d"),
  X_00010_00001=0,
  X_00010_00001_cd=0,
  X_00010_00003=0,
  X_00010_00003_cd= "",
  X_00060_00003=0,    
  X_00060_00003_cd= "",
  yr="",
  mo=0
  )
for (id in st_all_gage) {
  siteNumber <-  id 
  parameterCd <- c("00010","00060") 
  #00060: Discharge, cubic feet per second
  #00010	Physical	Temperature, water, degrees Celsius	
  ChoptankInfo <- readNWISsite(siteNumber)
 #ChoptankInfo$alt_va : Gage datum feet above NGVD29
  #statCd <- c("00003") 
  #00001 max
  #00003 mean
  startDate <- "1981-10-01"
  endDate <- "2023-09-30"
  meanT <-readNWISdv(siteNumber, parameterCd,startDate, endDate, statCd= c("00001","00003"))
  if (dim(meanT )[2]>5){
    meanT$yr<- format(meanT$Date, format = "%Y") 
    meanT$mo<-as.numeric(format(meanT$Date, format = "%m"))
    meanSummerT<-meanT[ ,c("agency_cd","site_no","Date"
                           ,"X_00010_00001"
                           ,"X_00010_00001_cd"
                           ,"X_00010_00003","X_00010_00003_cd","X_00060_00003","X_00060_00003_cd","yr","mo"  )]
#    meanAugT<-meanT[meanT$mo==8,c("agency_cd","site_no","Date","X_00010_00001","X_00010_00001_cd","X_00010_00003","X_00010_00003_cd","X_00060_00003","X_00060_00003_cd","yr","mo"  )]
    
    meanSummerT_df <-rbind(meanSummerT_df,meanSummerT)
    print(    paste(id,dim(meanT )[1],Sys.time() ) )
  }
}
summary(meanSummerT_df)
df<-meanSummerT_df[ !is.na(meanSummerT_df$X_00010_00003) &  !meanSummerT_df$mo<1 ,]
summary(df)
#saveRDS( df, file="USGS_13296000_ST_Q.rds")
```

```{r}
#saveRDS( df, file="USGS_13296000_ST_Q_2011_2023.rds")
#df<-readRDS("USGS_13296000_ST_Q.rds")
df<-readRDS("USGS_13296000_ST_Q_2011_2023.rds")
summary(df)
```

```{r}
table(df[df$mo %in% c(6,7,8),]$yr)
```

```{r}
prism$Date <-as.Date(prism$Date, format="%Y-%m-%d")
prism_df<-merge(prism,df,by.x="Date",by.y= "Date")
prism_df$X_00010_00003 -> prism_df$mean_StreamTemp
prism_df$X_00010_00001-> prism_df$max_StreamTemp
log(prism_df$X_00060_00003)->prism_df$log_mean_Q
prism_df$tmax..degrees.C.->prism_df$max_AirTemperature_C
prism_df$tmean..degrees.C.->prism_df$mean_AirTemperature_C
prism_df$max_AirTemperature_C_1<-0
prism_df$mean_AirTemperature_C_1<-0
for (i in 2:dim(prism_df)[1]) {
prism_df[ i,]$max_AirTemperature_C_1<-prism_df[ i-1 ,]$max_AirTemperature_C
prism_df[ i,]$mean_AirTemperature_C_1<-prism_df[ i-1 ,]$mean_AirTemperature_C
}
prism_df$vpdmax..hPa.->prism_df$vpdmax
prism_df$doy<-yday( prism_df$Date )
prism_df$yr<-as.numeric(prism_df$yr)
prism_df<-prism_df[,c("Date", "yr", "vpdmax", "mean_AirTemperature_C","mean_AirTemperature_C_1" #, "max_AirTemperature_C"
                      #, "max_AirTemperature_C_1"
                      ,"log_mean_Q", "max_StreamTemp", "mean_StreamTemp","mo","doy")]
summary(prism_df)
```

```{r}
table( prism_df[prism_df$mo %in% c(6,7,8),]$yr)
```

# Step 4: Load PRISM and USGS
```{r}
prism_df<-prism_df[!prism_df$yr==c(2017,2021,2022,2023),]
saveRDS( prism_df, file="prism_df_13296000_2012_2020.rds")
#prism_df<-readRDS("daily_df_summer_13311000.rds")
summary(prism_df)
```

```{r}
summer_months<-c("6","7","8")
prism_df2<-prism_df
prism_df2$yr<-as.character(prism_df$yr)
prism_df2$mo<-as.character(prism_df$mo)
max_ST_yr<-prism_df2 %>% group_by( yr ,  mo  )%>% summarise(max_ST = max(mean_StreamTemp),mean_ST=mean(mean_StreamTemp) )
max_ST_yr[max_ST_yr$mo %in%  summer_months ,]
boxplot(max_ST_yr[max_ST_yr$mo %in%  summer_months,]$mean_ST~max_ST_yr[max_ST_yr$mo %in%  summer_months,]$mo, ylab = "Monthly mean stream T (degC)", xlab="Month", main="YANKEE FORK SALMON RIVER NR CLAYTON ID")
```












# Step 5: specify year and month for analysis
```{r}
prism_df<-prism_df[   prism_df$mo %in%  summer_months,]
summary(prism_df)
```

# Step 6: Create the correlation plot
```{r}
prism_df ->daily_df_summer
daily_df_summer$log_median_Q<-daily_df_summer$log_mean_Q
M <-cor( daily_df_summer[,c("mean_StreamTemp"
#                            ,"max_StreamTemp"      
,"log_mean_Q","mean_AirTemperature_C","mean_AirTemperature_C_1" #,"max_AirTemperature_C_1","max_AirTemperature_C"
,"vpdmax","doy")])
M
corrplot(M, type="upper", order="hclust",
         col=brewer.pal(n=8, name="RdYlBu"))
M_1 <-cor( daily_df_summer[,c("mean_StreamTemp" ,"log_mean_Q","mean_AirTemperature_C")])
corrplot(M_1, type="upper", order="hclust",
         col=brewer.pal(n=8, name="RdYlBu"))
```

# Model 2: GBM
```{r}
# set seed for generating random data.
set.seed(0)          
# createDataPartition() function from the caret package to split the original dataset into a training and testing set and split data into training (80%) and testing set (20%)
variables<-c("mean_StreamTemp","mean_AirTemperature_C","log_mean_Q" )
parts = createDataPartition(  daily_df_summer$mean_StreamTemp , p = .8, list = F)
train = daily_df_summer[parts, variables ]
test =  daily_df_summer[-parts, variables  ]
# feature and target array
test_x = test[, -1] 
test_y = test[, 1] 
```

```{r}
model_gbm = gbm(train$mean_StreamTemp      ~.,
                data = train,
                distribution = "gaussian",
                cv.folds = 10,
                shrinkage = .01,
                n.minobsinnode = 10,
                n.trees = 400)
 
# model performance
perf_gbm1 = gbm.perf( model_gbm, method = "cv")
print(model_gbm)
summary(model_gbm)
rinf<-summary(model_gbm)
barplot( rinf$rel.inf , horiz = TRUE, las = 1)
ggplot(rinf, aes(rel.inf)) + geom_bar()
rinf$max_yr<-max(as.numeric(daily_df_summer$yr))
rinf$min_yr<-min(as.numeric(daily_df_summer$yr))
rinf$site_id<- 13296000
rinf
saveRDS(rinf ,file=  "rinf_13296000.rds"  )
```

```{r}
rinf$var<- factor(rinf$var, levels=c(  "mean_AirTemperature_C","log_mean_Q"  ))
ggplot( rinf, aes( var , rel.inf ))+  geom_col()+ 
  coord_flip()
ggplot( rinf )+  geom_bar(  aes( x=var, y= rel.inf),  stat = "summary")+ scale_x_discrete(labels=  c( "mean_AirTemperature_C","log_mean_Q") )+ylab("Relative importance (%)") +xlab(" ")  + theme(text=element_text(size=16))
```

```{r}
#test_y <-test_y$max_StreamTemp
pred_y = predict.gbm(model_gbm, test_x)
residuals =  test_y   - pred_y
summary(test_y )
xlim=c(5,20)
RMSE = sqrt(mean(residuals^2))
cat('The root mean square error of the test data is ', round(RMSE,3),'\n')
y_test_mean = mean( test_y  )
# Calculate total sum of squares
tss =  sum(( test_y   - y_test_mean)^2 )
# Calculate residual sum of squares
rss =  sum(residuals^2)
# Calculate R-squared
rsq  =  1 - (rss/tss)
cat('The R-square of the test data is ', round(rsq,3), '\n')
# visualize the model, actual and predicted data
x_ax = 1:length(pred_y)
plot(x_ax, test_y  , col="blue", pch=20, cex=.9)
lines(x_ax, pred_y, col="red", pch=20, cex=.9) 
plot(  test_y , pred_y,xlim= xlim ,ylim= xlim, xlab="Observed stream temperature (degC)", ylab="Predicted stream temperature (degC)", main="YANKEE FORK SALMON RIVER NR CLAYTON ID")
par(new=T)
x=seq(1,30)
plot(x,x,type="l",xlim= xlim ,ylim= xlim,xlab="",ylab="")
```

```{r}
# ts function is responsible to convert to ts object
daily_df_summer_2017<-daily_df_summer[daily_df_summer$yr==2020,]
ts <- ts(data = daily_df_summer_2017[, c( "mean_AirTemperature_C",  "mean_StreamTemp" )], # selecting 2 variables
   start = 1,
   end =  dim(daily_df_summer_2017)[1],
   frequency = 1)
ts
```

```{r}
ts_plot( ts,
        title = "YANKEE FORK SALMON RIVER NR CLAYTON ID",
        Ytitle =    "mean StreamTemp",
        Xtitle = " ", )
```

```{r}
summer_ts_2020<-daily_df_summer[daily_df_summer$yr==2020,]
summer_ts_2020

ylim=ylim(0,25)

ggplot(summer_ts_2020[,c("Date","mean_AirTemperature_C")], aes( Date,mean_AirTemperature_C) ) +
  geom_point(color = "red"   ) +
  ylim+
# geom_smooth()+
 # stat_smooth()+
  geom_point(data = summer_ts_2020[,c("Date","mean_StreamTemp") ], aes(x = Date  , y =  mean_StreamTemp) , color = "dodgerblue"  ) +
ylim +
  #stat_smooth()+
ggtitle("YANKEE FORK SALMON RIVER NR CLAYTON ID")+
  ylab("Temperature (degC)")+
  labs()

```


```{r}
# ccf time series
par(mfrow=c(1,1))
ccf( ts[, c( "mean_StreamTemp")],  ts[, c( "mean_AirTemperature_C")], 
    lag.max = 11,
    main = "Cros-Correlation Plot",
    ylab = "CCF")
# ccf time series
par(mfrow=c(1,1))
ccf( ts[, c( "mean_AirTemperature_C")],  ts[, c( "mean_StreamTemp")], 
    lag.max = 11,
    main = "Cros-Correlation Plot",
    ylab = "CCF")
```

